mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 10.202.10.202
    - 178.22.122.100
  enhanced-mode: fake-ip
  nameserver:
    - 10.202.10.202
    - 178.22.122.100
  fallback:
    - 64.6.64.6
    - 64.6.65.6
  fallback-filter:
    geoip: true
    geoip-code: IR
proxies:

proxy-groups:
  - name: Core
    type: select
    proxies:
   
  - name: Ping
    type: url-test
    url: http://detectportal.firefox.com/
    interval: 600
    tolerance: 50
    lazy: false
    proxies:

rule-providers:
  direct:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Airuop/servers/main/rules/direct.yaml
    path: ./ruleset/direct.yaml
    interval: 432000
  block:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Airuop/servers/main/rules/block.yaml
    path: ./ruleset/block.yaml
    interval: 432000
rules:
  - RULE-SET,direct,DIRECT
  - RULE-SET,block,REJECT
  - MATCH,Core
